"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['bmux.py']
DATA_FILES = ['data', 'images', 'scripts']
OPTIONS = {
        'iconfile': 'images/standard_icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
